version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-tango-web
    restart: always
    env_file: .env
    environment:
      - PORT=3006
    ports:
      - "3006:3006"
    extra_hosts:
      - "host-gateway:host-gateway"
